create table if not exists public.bay_area_locations (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  region text not null,
  city text not null,
  neighborhood text,
  description text not null,
  best_for text not null,
  best_time text not null,
  tip text not null,
  tags text[] not null default '{}'::text[],
  image_url text,
  "order" integer not null default 1,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists bay_area_locations_region_order_idx
on public.bay_area_locations (region, "order");

create or replace function public.set_bay_area_locations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists bay_area_locations_set_updated_at
on public.bay_area_locations;

create trigger bay_area_locations_set_updated_at
before update on public.bay_area_locations
for each row
execute function public.set_bay_area_locations_updated_at();
