create table if not exists public.portfolio_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  sort_order integer not null default 1,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.portfolio_images (
  id bigint generated by default as identity primary key,
  title text not null,
  alt text,
  image_url text not null,
  category_id bigint references public.portfolio_categories(id) on delete set null,
  category_slug text not null default 'portfolio',
  featured boolean not null default false,
  sort_order integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.blog_posts
add column if not exists category text not null default 'journal';

create index if not exists portfolio_categories_active_order_idx
on public.portfolio_categories (active, sort_order);

create index if not exists portfolio_images_category_order_idx
on public.portfolio_images (category_slug, sort_order);

create index if not exists portfolio_images_featured_order_idx
on public.portfolio_images (featured, sort_order);

create index if not exists blog_posts_category_published_idx
on public.blog_posts (category, published_at desc);

create or replace function public.set_professional_portfolio_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists portfolio_categories_set_updated_at
on public.portfolio_categories;

create trigger portfolio_categories_set_updated_at
before update on public.portfolio_categories
for each row
execute function public.set_professional_portfolio_updated_at();

drop trigger if exists portfolio_images_set_updated_at
on public.portfolio_images;

create trigger portfolio_images_set_updated_at
before update on public.portfolio_images
for each row
execute function public.set_professional_portfolio_updated_at();

update public.portfolio_images
set category_slug = 'grads'
where category_slug = 'graduation';

update public.portfolio_images
set category_slug = 'families'
where category_slug = 'portraits';

update public.portfolio_categories
set active = false
where slug in ('graduation', 'portraits', 'events');

insert into public.portfolio_categories (name, slug, description, sort_order, active)
values
  ('Grads', 'grads', 'Clean Bay Area graduation portraits with a soft editorial feel.', 1, true),
  ('Families', 'families', 'Warm family sessions for the people and moments you want to keep.', 2, true),
  ('Couples', 'couples', 'Couples sessions, held quietly for a future portfolio section.', 3, false)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  active = excluded.active,
  updated_at = timezone('utc', now());

alter table public.portfolio_categories enable row level security;
alter table public.portfolio_images enable row level security;

drop policy if exists "portfolio_categories_public_read"
on public.portfolio_categories;

create policy "portfolio_categories_public_read"
on public.portfolio_categories
for select
using (true);

drop policy if exists "portfolio_categories_public_write"
on public.portfolio_categories;

create policy "portfolio_categories_public_write"
on public.portfolio_categories
for all
using (true)
with check (true);

drop policy if exists "portfolio_images_public_read"
on public.portfolio_images;

create policy "portfolio_images_public_read"
on public.portfolio_images
for select
using (true);

drop policy if exists "portfolio_images_public_write"
on public.portfolio_images;

create policy "portfolio_images_public_write"
on public.portfolio_images
for all
using (true)
with check (true);
