create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.image_library (
  id bigint generated by default as identity primary key,
  title text not null,
  alt text null,
  image_url text not null,
  storage_path text null,
  source_type text not null,
  source_post_id bigint null references public.blog_posts(id) on delete set null,
  source_post_slug text null,
  source_role text not null,
  in_portfolio boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint image_library_title_not_blank check (length(trim(title)) > 0),
  constraint image_library_image_url_not_blank check (length(trim(image_url)) > 0),
  constraint image_library_source_type_not_blank check (length(trim(source_type)) > 0),
  constraint image_library_source_role_not_blank check (length(trim(source_role)) > 0)
);

drop trigger if exists image_library_set_updated_at on public.image_library;

create trigger image_library_set_updated_at
before update on public.image_library
for each row
execute function public.set_updated_at();

create unique index if not exists image_library_source_dedupe_idx
on public.image_library (source_post_id, source_role, image_url);

create index if not exists image_library_source_post_id_idx
on public.image_library (source_post_id);

create index if not exists image_library_in_portfolio_idx
on public.image_library (in_portfolio);

create index if not exists image_library_image_url_idx
on public.image_library (image_url);

create or replace function public.is_image_library_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

alter table public.image_library enable row level security;

drop policy if exists "Admins can view image library" on public.image_library;
create policy "Admins can view image library"
on public.image_library
for select
to authenticated
using (public.is_image_library_admin());

drop policy if exists "Admins can create image library rows" on public.image_library;
create policy "Admins can create image library rows"
on public.image_library
for insert
to authenticated
with check (public.is_image_library_admin());

drop policy if exists "Admins can update image library rows" on public.image_library;
create policy "Admins can update image library rows"
on public.image_library
for update
to authenticated
using (public.is_image_library_admin())
with check (public.is_image_library_admin());

drop policy if exists "Admins can delete image library rows" on public.image_library;
create policy "Admins can delete image library rows"
on public.image_library
for delete
to authenticated
using (public.is_image_library_admin());

revoke all on public.image_library from anon, authenticated;
grant select, insert, update, delete on public.image_library to authenticated;
grant usage, select on sequence public.image_library_id_seq to authenticated;
